### ISSUE TITLE
python3.5 breaks colcon build in Ubuntu <18.04

### ISSUE THREAD

**Issue by audreyseo** [cmu-mars/ros1-to-ros2-sandbox#5]
In the fix4 branch (currently not pushed to remote but I can), trying to build the Dockerfile results in the following error output during colcon build:

```
Starting >>> rmw
Finished <<< yaml_cpp_vendor Æ29.3sÅ
Starting >>> rcl_logging_log4cxx
Finished <<< rcl_logging_log4cxx Æ2.83sÅ
Starting >>> rcl_logging_noop
Finished <<< rcl_logging_noop Æ2.19sÅ
Starting >>> pluginlib
--- stderr: orocos_kdl
/home/docker/ros2_ws/src/ros2/orocos_kinematics_dynamics/orocos_kdl/src/trajectory.cpp: In static member function ‘static KDL::Trajectory* KDL::Trajectory::Read(std::istream&)’:
/home/docker/ros2_ws/src/ros2/orocos_kinematics_dynamics/orocos_kdl/src/trajectory.cpp:65:3: error: ‘unique_ptr’ was not declared in this scope
   unique_ptr<Path>      geom(    Path::Read(is)       );
   ^
/home/docker/ros2_ws/src/ros2/orocos_kinematics_dynamics/orocos_kdl/src/trajectory.cpp:65:18: error: expected primary-expression before ‘>’ token
   unique_ptr<Path>      geom(    Path::Read(is)       );
                  ^
/home/docker/ros2_ws/src/ros2/orocos_kinematics_dynamics/orocos_kdl/src/trajectory.cpp:65:55: error: ‘geom’ was not declared in this scope
   unique_ptr<Path>      geom(    Path::Read(is)       );
                                                       ^
/home/docker/ros2_ws/src/ros2/orocos_kinematics_dynamics/orocos_kdl/src/trajectory.cpp:66:29: error: expected primary-expression before ‘>’ token
   unique_ptr<VelocityProfile> motprof( VelocityProfile::Read(is)  );
                             ^
/home/docker/ros2_ws/src/ros2/orocos_kinematics_dynamics/orocos_kdl/src/trajectory.cpp:66:67: error: ‘motprof’ was not declared in this scope
   unique_ptr<VelocityProfile> motprof( VelocityProfile::Read(is)  );
                                                                   ^
makeÆ2Å: *** Æsrc/CMakeFiles/orocos-kdl.dir/trajectory.cpp.oÅ Error 1
makeÆ1Å: *** Æsrc/CMakeFiles/orocos-kdl.dir/allÅ Error 2
make: *** ÆallÅ Error 2
---
Failed   <<< orocos_kdl	Æ Exited with code 2 Å
Aborted  <<< pluginlib
Æ157.323sÅ ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<_wait_and_close_fds() done, defined at /usr/lib/python3/dist-packages/colcon_core/subprocess.py:253> exception=RuntimeError('cannot reuse already awaited coroutine',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
RuntimeError: cannot reuse already awaited coroutine
Æ165.313sÅ ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<_wait_and_close_fds() done, defined at /usr/lib/python3/dist-packages/colcon_core/subprocess.py:253> exception=RuntimeError('cannot reuse already awaited coroutine',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
RuntimeError: cannot reuse already awaited coroutine
Aborted  <<< rmw
Aborted  <<< fastrtps
Æ221.735sÅ ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<_pipe2callback() done, defined at /usr/lib/python3/dist-packages/colcon_core/subprocess.py:238> wait_for=<Future pending cb=ÆTask._wakeup()Å> cb=Æ_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:414Å>

Summary: 74 packages finished Æ3min 41sÅ
  1 package failed: orocos_kdl
  3 packages aborted: fastrtps pluginlib rmw
  6 packages had stderr output: opensplice_cmake_module orocos_kdl poco_vendor python_qt_binding rosidl_adapter rosidl_parser
  179 packages not processed
Æ222.238sÅ ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<_pipe2callback() done, defined at /usr/lib/python3/dist-packages/colcon_core/subprocess.py:238> wait_for=<Future pending cb=ÆTask._wakeup()Å> cb=Æ_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:414Å>
Æ222.239sÅ ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<_pipe2callback() done, defined at /usr/lib/python3/dist-packages/colcon_core/subprocess.py:238> wait_for=<Future pending cb=ÆTask._wakeup()Å> cb=Æ_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:414Å>
The command '/bin/sh -c colcon build --symlink-install --packages-ignore qt_gui_cpp rqt_gui_cpp --packages-skip ros1_bridge' returned a non-zero code: 2
```

It may be worth it to try to just build opencv3 for melodic, instead of trying to use kinetic, since I found [this ROS issue describing the same thing](https://github.com/colcon/colcon-core/issues/138), and they essentially have not fixed it yet.
